import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'}
  ],
  
  // Tutorials sidebar
  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'Tutorials/introduction',
        {
          type: 'category',
          label: 'Account',
          items: ['Tutorials/Account/invite-team-members'],
        },
        {
          type: 'category',
          label: 'Accounting',
          items: ['Tutorials/Accounting/record-an-expense'],
        },
        {
          type: 'category',
          label: 'Banking',
          items: ['Tutorials/Banking/how-to-import-bank', 'Tutorials/Banking/how-to-connect-salt-edge'],
        },
        {
          type: 'category',
          label: 'Invoicing',
          items: ['Tutorials/Invoicing/how-to-customize-language'],
        }
      ],
    },
  ],
};

export default sidebars;