import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'}
  ],
  
  // Tutorials sidebar
  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'Tutorials/introduction',
        {
          type: 'category',
          label: 'General Tutorials',
          items: ['Tutorials/account/invite-team-members'],
        },
        {
          type: 'category',
          label: 'Banking Tutorials',
          items: ['Tutorials/banking/how-to-import-bank', 'Tutorials/banking/how-to-connect-salt-edge'],
        }
      ],
    },
  ],
};

export default sidebars;